### PR TITLE
Fix #224 and fix #19: Add SuperType and resolve super.m calls.

### LINKED ISSUE #19: Support SUPERtype Type Tag

### LINKED ISSUE #224: Super selects without SelectIn's don't point to the right symbol
Test source `Super.scala`:
```scala
package simple_trees

class Base {
  def f(): Unit = ()
  def g: Int = 2
}

class Super extends Base {
  override def f(): Unit = ()
  override def g: Int = 3

  def callMyF(): Unit = f()

  def callBareSuperF(): Unit = super.f()
  def callQualifiedSuperF(): Unit = super[Base].f()

  def callMyG(): Int = g

  def callBareSuperG(): Int = super.g
  def callQualifiedSuperG(): Int = super[Base].g
}
```
Unit test for `TypeSuite.scala`:
```scala
  testWithContext("super calls") {
    val BaseClass = ctx.findTopLevelClass("simple_trees.Base")
    val SuperClass = ctx.findTopLevelClass("simple_trees.Super")

    def rhsOf(methodName: String): TermTree =
      SuperClass.findNonOverloadedDecl(termName(methodName)).tree.get.asInstanceOf[DefDef].rhs.get

    val fInBase = BaseClass.findNonOverloadedDecl(termName("f"))
    val fInSuper = SuperClass.findNonOverloadedDecl(termName("f"))

    locally {
      val rhs @ Apply(select: Select, Nil) = rhsOf("callMyF"): @unchecked
      assert(clue(select.symbol) == clue(fInSuper))
    }

    locally {
      val rhs @ Apply(select: Select, Nil) = rhsOf("callBareSuperF"): @unchecked
      assert(clue(select.symbol) == clue(fInBase))
    }

    locally {
      val rhs @ Apply(select: Select, Nil) = rhsOf("callQualifiedSuperF"): @unchecked
      assert(clue(select.symbol) == clue(fInBase))
    }

    val gInBase = BaseClass.findNonOverloadedDecl(termName("g"))
    val gInSuper = SuperClass.findNonOverloadedDecl(termName("g"))

    locally {
      val select @ (_: Select) = rhsOf("callMyG"): @unchecked
      assert(clue(select.symbol) == clue(gInSuper))
    }

    locally {
      val select @ (_: Select) = rhsOf("callBareSuperG"): @unchecked
      assert(clue(select.symbol) == clue(gInBase))
    }

    locally {
      val select @ (_: Select) = rhsOf("callQualifiedSuperG"): @unchecked
      assert(clue(select.symbol) == clue(gInBase))
    }
  }
```
Fails for `callBareSuperG` and `callQualifiedSuperG`.

This might be the reason we actually need `SuperType`s.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala [hunk 1]
```diff
@@ -1051,6 +1051,14 @@ private[tasties] class TreeUnpickler(
...
       // Type of QUALTHIS is ThisType for the type reference, which is the type of the IDENTtpt
       ThisType(readType.asInstanceOf[TypeRef])
+    case SUPERtype =>
+      reader.readByte()
+      reader.readEnd()
+      val thistpe = readType match
+        case thistpe: ThisType => thistpe
+        case thistpe           => throw TastyFormatException(s"Unexpected this type for SuperType: $thistpe")
+      val supertpe = readType
+      SuperType(thistpe, Some(supertpe))
```
Comment (bishabosha) [inline tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala:1061]: why is explicitSupertpe optional?

Comment (bishabosha) [reply tasty-query/shared/src/main/scala/tastyquery/reader/tasties/TreeUnpickler.scala:1061]: oh yeah because of trees
