### PR TITLE
read match types in tasty unpickler

### LINKED ISSUE #17: Support MATCHtype Type Tag
Currently, MATCHtype tag is not supported by TreeUnpickler.

### LINKED ISSUE #18: Support MATCHCASEtype Type Tag

### LINKED ISSUE #134: Cannot read `MATCHtpe`
Adding this in `simple_trees/MatchType`

```scala
  def m[X](x: X): MT[X] = x match
    case i: Int => i.toString

  val v = m(5)
```

I got:
```
    ==> X tastyquery.ReadTreeSuite.match-type  0.005s tastyquery.reader.TreeUnpicklerException: Unexpected type tag MATCHtype at address Addr(280) in file /home/piquerez/github/scalacenter/tasty-query/test-sources/target/scala-3.1.0/classes/simple_trees/MatchType.tasty
    at tastyquery.reader.TreeUnpickler.readType(TreeUnpickler.scala:1053)
    at tastyquery.reader.TreeUnpickler.readTypeTree(TreeUnpickler.scala:1157)
    at tastyquery.reader.TreeUnpickler.readTerm$$anonfun$1(TreeUnpickler.scala:656)
    at dotty.tools.tasty.TastyReader.until(TastyReader.scala:125)
    at tastyquery.reader.TreeUnpickler.readTerm(TreeUnpickler.scala:656)
    at tastyquery.reader.TreeUnpickler.readValOrDefDef(TreeUnpickler.scala:594)
```

The crash happens on reading the `val v`.

### PR DESCRIPTION
**Pull request by bishabosha**
fixes #17 
fixes #18 
fixes #134

### CODE REVIEW

File: tasty-query/shared/src/main/scala/tastyquery/Types.scala [hunk 1]
```diff
@@ -1339,6 +1339,18 @@ object Types {
       new RecType(parentExp) // TODO? Perform normalization like dotc?
   end RecType
 
+  /** case `pattern` => `result` */
+  final class MatchTypeCase(val pattern: Type, val result: Type) extends GroundType:
+    def findMember(name: Name, pre: Type)(using Context): Symbol = NoSymbol
+    override def toString(): String = s"MatchTypeCase($pattern, $result)"
+
+  /** selector match { cases } */
```
Comment (sjrd) [inline tasty-query/shared/src/main/scala/tastyquery/Types.scala:1347]: Could you add `end` markers for the `class`es that are not one-liners?

**Review by sjrd — APPROVED** [review]
