### PR TITLE
Fix/companion lookup

### LINKED ISSUE #184: enable companion lookup methods for non static classes
currently you can only lookup the companion object of a class if the class owner is a package

### PR DESCRIPTION
**Pull request by guihardbastien**
fixes #184

### CODE REVIEW

File: tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala [hunk 1]
```diff
@@ -1256,4 +1256,26 @@ class TypeSuite extends UnrestrictedUnpicklingSuite {
...
+  def companionClassFullCycle(path: DeclarationPath)(using Context, munit.Location): Unit = {
+    val Class: ClassSymbol = resolve(path).asClass
+    val Object: ClassSymbol = resolve(path.asObj).asClass
+
+    assert(Object == Class.companionClass.get)
+    assert(Object.companionClass.get == Class)
+  }
+
+  testWithContext("companion-tests-module-value") {
+    val x: Any = name"companions" / tname"CompanionObject"
```
Comment (sjrd) [inline tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala:1269]: This is unused.

File: tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala [hunk 2]
```diff
@@ -1256,4 +1256,26 @@ class TypeSuite extends UnrestrictedUnpicklingSuite {
     assert(clue(childToString.allOverriddenSymbols.toList) == List(superToString, objectToString))
     assert(clue(childToString.nextOverriddenSymbol) == Some(superToString))
   }
+
+  def companionClassFullCycle(path: DeclarationPath)(using Context, munit.Location): Unit = {
+    val Class: ClassSymbol = resolve(path).asClass
+    val Object: ClassSymbol = resolve(path.asObj).asClass
```
Comment (sjrd) [inline tasty-query/shared/src/test/scala/tastyquery/TypeSuite.scala:1262]: `Class` and `Object` are well-known things in `java.lang`, so those names are a bit confusing. Consider using `cls` and `moduleClass` instead, which would follow the convention used in the codebase.

**Review by sjrd — CHANGES_REQUESTED** [review]
Very good tests, thanks.

Could you also squash all the commits in a single one. Merge commits in particular should be avoided in a PR branch.

**Review by sjrd — APPROVED** [review]
Congrats 🎉
